Team 5 Hello world graph
nyuoss/ninja-shadowdash-nyu pull request #10
Opened 2024-10-10 15:29 UTC by qianxichen233

This PR is an experiment that adds a build option to Ninja, allowing it to skip the parsing step (i.e., parsing `build.ninja`) and instead manually set up the dependency graph in memory, passing it directly to `runBuild`.

To use it, after building Ninja, run `./ninja hello` inside the `hello_world_graph` folder. This will generate the "Hello World" binary without the need for a `build.ninja` file.

---

#### Why use a command-line option (i.e., requiring `hello` to be passed to `ninja`) instead of creating a separate build binary specifically for the "Hello World" program (e.g., running `./ninja_hello` directly in the `hello_world_graph` folder)?

While it is possible to create a dedicated binary, which would be clearer, all the relevant classes like `NinjaMain` exist only in `ninja.cc`, and there isn’t something like a `ninja.h` header file. In order to use `NinjaMain` to continue the build process after the graph is created, we would need to refactor `ninja.cc` into a header file (`ninja.h`) so that other source files could utilize `NinjaMain`.

Since I guess this task is more of an experiment, I have not done that refactoring at this point.

2024-11-04 03:49 UTC, waynewangyuxuan commented
This is very smart work, directly adding it as a part of the source code rather than create a stand alone script that uses the source code as an external library.
The functionality is definitely sufficed.
Very easy to follow and to read and understand your workflow.
Linting definitely passes. Clean cpp code.
The test cases covers the necessary aspects, essentially, the graph creation code, which is a part of ninja, thus ninja_test would work.

2024-11-25 00:31 UTC, YuWei-CH reviewed
Here is the new PR reviews for mini-task, comments by @waynewangyuxuan and @Yuwei-CH.
Your team’s code is highly refined and well-strctured. And I only have a small suggestion: when submitting a PR, consider including screenshots of the **CircleCI** results. This would help reviewers better understand your test plan. In addition, it can prove that your code conforms to established style guides, for example pass clang-tidy checks.

2024-11-25 00:31 UTC, YuWei-CH commented on hello_world_graph/ninja
> +../build-cmake/ninja
Hi, this symbolic link can be add to .gitignore. The path to the executable Ninja file can vary depending on where the user builds it. For instance, some users may build Ninja in the _../build_ directory.

2024-11-25 00:31 UTC, YuWei-CH commented on src/ninja.cc
1. **Change Granularity**: Code are well-segmented and serve distinct purpose. :white_check_mark:
2. **Code Functionality**: This functionality aligns with the task’s requirements. :white_check_mark:

2024-11-25 00:31 UTC, YuWei-CH commented on src/ninja.cc
> +void compile_hello(int argc, char** argv) {
**_Readability & Structure_**: Adding comments inside the compile_hello() function to explain its logic can help others better understand the purpose and flow of the function.

2024-11-25 00:31 UTC, YuWei-CH commented on src/ninja.cc
> +  // edge_compile->outputs_.reserve(1);
Is this comments set to explain the code below?

2024-11-25 00:31 UTC, YuWei-CH commented on src/ninja.cc
> +extern void compile_hello(int argc, char** argv);
Is this **_extern **_declaration_**_** necessary? Since this function is already defined in the same file, the compiler will find its implementation directly.

2024-11-25 00:31 UTC, YuWei-CH commented on src/ninja.cc
> +    compile_hello(argc, argv);
**API Exposure**: All functionality is encapsulated within compile_hello, that's pretty good. :white_check_mark:

2024-11-27 02:24 UTC, kyotov requested changes
looks pretty good overall.
address existing comments and let me know to look again.

one thing that you might want to consider in the spirit of the class is to create an api for the graph that you call... or at least document the current one? WDYT?

2024-11-27 02:24 UTC, kyotov commented on src/ninja.cc
> +  value1.AddText(" ");
why are these 4 separate calls?

2024-12-04 21:13 UTC, qianxichen233 commented
> looks pretty good overall. address existing comments and let me know to look again.
> 
> one thing that you might want to consider in the spirit of the class is to create an api for the graph that you call... or at least document the current one? WDYT?

Yeah, I guess all comments are resolved. For the API exposure, I believe the description of the PR already documented the current api usage (i.e. how to invoke via command line). And I also mentioned the potential approach that directly expose the hello graph api as an dedicated binary. This is actually already achieved in the PR for shadowdash demo, since I need to create a dedicated binary for shadowdash, so I just did the same for hello gragh by the way.

2024-12-11 20:42 UTC, waynewangyuxuan commented
# Final PR review
## Change Granularity
The commits are squashed into one, very easy to track changes. Since this is a single task without many distinctive components, one commit suffice. 
## Code Functionality
Code works. Logics are clear and well-designed. 
##Readability & Structure
One function required (one functionality required), one function created, well encapsulated. Naming is intuitive enough for others to understand. Could make use of more comments within the function to better explain the workflow maybe?
##Standards Compatibility
Linting passes. Very clean C++ code written. Regarding test, I believe it is not applicable in this case.
##AP Exposure
Mostly addressed by previous comment. Consider it resolved.

##Overall
Great work. Nice implementation.

2024-12-13 03:22 UTC, qianxichen233 commented
moved to https://github.com/nyuoss/ninja-shadowdash-nyu/pull/30

2024-12-13 03:22 UTC, closed without merging