team-4-new-graph
nyuoss/ninja-shadowdash-nyu pull request #9
Opened 2024-10-08 02:04 UTC by waynewangyuxuan

Commits Merged.
Resulting graphs are saved in the folder /steps.

2024-11-01 17:39 UTC, Yaxuan-w commented on CMakeLists.txt
> +# Set shared library properties
Could you please add more detailed explanation about the functionality of those code in comment..?

2024-11-01 18:00 UTC, Yaxuan-w reviewed
Collaborate with Qianxi Chen @qianxichen233

Great job! Few minor suggestions:
1. Directory is a bit messy, would be great to have a README.md for high-level description or add it in description section of this PR
2. Duplicated file name and no instructions about their usage. It would be better to use more descriptive file names / detailed comment at beginning of the file / add READMEs 
3. Lots of commits, would be great to do squash merge here

2024-11-01 18:00 UTC, Yaxuan-w commented on commands.md
> +export PATH=$PATH:/home/yuwei/Documents/llvm-project/build/bin
It should be better to use a more general `PATH` instead of a personal one?

2024-11-01 18:00 UTC, Yaxuan-w commented on commands.md
It seems like a setup script but the file is in markdown format. Is there any specific reason for this?

2024-11-01 18:00 UTC, Yaxuan-w commented on src/manifest_parser.h
> +  bool ParsePool(std::string* err); // wokers
What's the meaning of `workers`?

2024-11-01 18:00 UTC, Yaxuan-w commented on src/test1.cc
> +
That would be great to have a more high-level comment that describing the functionality of this file

2024-11-01 18:00 UTC, Yaxuan-w commented on src/test1.cc
> +  return 0;
Is there any reason to have two `return` here?

2024-11-01 18:00 UTC, Yaxuan-w commented on steps/hello-world-graph/commands.md
1. Seems like a script, why markdown here?
2. Would be great to replace all absolute personal path. i.e.: `/home/yuwei/Documents/ShadowDash/build`

2024-11-01 18:00 UTC, Yaxuan-w commented on steps/hello-world-graph/test1.cc
1. What's the purpose of this file?
2. What's difference with `src/test1.cc` and they have the same name. That would be great to have a high level description and use a more descriptive file name here.

2024-11-01 18:00 UTC, Yaxuan-w commented on test1
The binary is not necessary..?

2024-11-03 02:57 UTC, waynewangyuxuan commented on steps/hello-world-graph/commands.md
because it is what yuwei used for testing at the time. The  personal path is there because it is command for this linux system, whereas the rest of us, if I am not mistakenly, has one person on MacOS and one on linux. 

This is not designed to be directly runnable, but more for a guidance for the rest of us to test the intermediate work at the time.

2024-11-03 02:58 UTC, waynewangyuxuan commented on test1
which binary are you referring to?

2024-11-03 02:58 UTC, waynewangyuxuan commented on steps/hello-world-graph/test1.cc
you are absolutely right. This is test1.cc is essentially what we are working with.  
the src one should be disregarded.

2024-11-03 02:59 UTC, waynewangyuxuan commented on src/test1.cc
> +
definitely, nice call!

2024-11-03 03:00 UTC, waynewangyuxuan commented on commands.md
we were using this as an internall readme honestly...but you are right, this is not very tidy

2024-11-04 03:48 UTC, YuWei-CH commented on CMakeLists.txt
> +# Set shared library properties
Thanks for your comments. The purpose of the code above is to generate a .so with the ninja files we need during the build Ninja process. We later realized that this is not necessary, so we will remove it in the next commits.

2024-11-04 03:51 UTC, YuWei-CH commented on commands.md
> +export PATH=$PATH:/home/yuwei/Documents/llvm-project/build/bin
Yes, thank you for pointing that out.

2024-11-04 03:53 UTC, YuWei-CH commented on test1
Yes, this is an executable file for generating new-graph. And we will add our internal used command.md and all binary files to the .gitignore. Thank you so much for pointing out those issues.

2024-11-27 02:21 UTC, kyotov requested changes
This suffers from some of the common problems I have noticed before.

* How is each file in your PR connected to the task at hand?  
  * You should not have files that are irrelevant to the task.  
* Make sure files that should be .gitignore are in .gitignore  
  * E.g. .DS\_Store  
* Make sure secrets are not checked in\!  
* Make sure there is a clear and separated API\!

Not all of these apply to you but some do.
Please address them and let me know and I will look again.

2024-11-27 02:21 UTC, kyotov commented on CMakeLists.txt
> +add_test(NAME NinjaTest COMMAND ninja_test)
there are more tests than this

2024-11-27 02:21 UTC, kyotov commented on steps/hello-world-graph/test1.cc
> +void CreateHelloWorldGraph(State* state) {
this is pretty good!@

2024-11-27 02:21 UTC, kyotov commented on CMakeLists.txt
> +# Set shared library properties
yes, remove

2024-12-04 20:04 UTC, Yaxuan-w commented
Collaborate with Qianxi Chen @qianxichen233:
Do you guys have any update commits after professor's comment? That would be great if you can point us to the new place, thanks!

2024-12-04 20:44 UTC, waynewangyuxuan commented
> Collaborate with Qianxi Chen @qianxichen233: Do you guys have any update commits after professor's comment? That would be great if you can point us to the new place, thanks!

Hi, no updates since. We were not sure what the professor meant by the comments, hoping to get a clearer clue during class today and we will make updates ASAP long as we know what he meant. Thanks for asking!

2024-12-06 21:40 UTC, closed without merging